language: node_js
node_js:
  - "0.12"
env:
  - PHANTOMJS_PATH=/usr/local/phantomjs/bin/phantomjs
after_success:
  - codeclimate-test-reporter < ./test/unit-test-coverage/lcov.info
addons:
    code_climate:
        repo_token: 596103895774c782916a7e4137eb4b2dcd9f59818096d20921adec266a7202b8